customhost = "employee.cowgsxsn8wpw.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "12345678"
customdb = "employee"
custombucket = "leejunyan-bucket"
profilebucket = "profile-picture/"
customregion = "us-east-1"
